from __future__ import annotations

import json
import math
import sys
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages"))

from resonancelab.dsp import ChirpSpec, generate_log_chirp  # noqa: E402

FIXTURES_DIR = ROOT / "services" / "api" / "tests" / "fixtures"
CROSS_LANGUAGE_SAMPLE_INDICES = [
    0,
    1,
    2,
    39,
    40,
    41,
    78,
    79,
    80,
    81,
    120,
    200,
    399,
    400,
    401,
    598,
    599,
    600,
    718,
    719,
    720,
    758,
    759,
    760,
    797,
    798,
    799,
]


def main() -> int:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    write_cross_language_chirp_fixture()
    write_recorded_style_probe_fixture()
    return 0


def write_cross_language_chirp_fixture() -> None:
    sample_rate_hz = 8000
    config = {
        "signal_type": "log_chirp",
        "start_hz": 300,
        "end_hz": 2400,
        "duration_ms": 100,
        "pre_roll_ms": 0,
        "post_roll_ms": 100,
        "amplitude": 0.35,
        "fade_ms": 10,
    }
    samples = generate_log_chirp(
        ChirpSpec(
            start_hz=float(config["start_hz"]),
            end_hz=float(config["end_hz"]),
            duration_seconds=float(config["duration_ms"]) / 1000.0,
            amplitude=float(config["amplitude"]),
            fade_seconds=float(config["fade_ms"]) / 1000.0,
        ),
        sample_rate_hz,
    ).astype(np.float32)

    payload = {
        "name": "cross_language_log_chirp_8khz_100ms",
        "description": (
            "Selected golden Float32 chirp samples generated by the Python DSP reference. "
            "Used by Python and TypeScript tests to keep browser playback and server "
            "matched-filter reference aligned, especially at cosine fade endpoints."
        ),
        "sample_rate_hz": sample_rate_hz,
        "config": config,
        "atol": 1e-7,
        "sample_indices": CROSS_LANGUAGE_SAMPLE_INDICES,
        "samples": [float(samples[index]) for index in CROSS_LANGUAGE_SAMPLE_INDICES],
    }
    write_json(FIXTURES_DIR / "cross_language_log_chirp.json", payload)


def write_recorded_style_probe_fixture() -> None:
    sample_rate_hz = 48000
    pre_roll_seconds = 0.25
    chirp_seconds = 0.50
    post_roll_seconds = 0.90
    acoustic_delay_seconds = 0.0075
    start_hz = 500.0
    end_hz = 10000.0
    amplitude = 0.35
    fade_seconds = 0.01
    noise_seed = 29

    samples = build_recorded_style_probe(
        sample_rate_hz=sample_rate_hz,
        pre_roll_seconds=pre_roll_seconds,
        chirp_seconds=chirp_seconds,
        post_roll_seconds=post_roll_seconds,
        acoustic_delay_seconds=acoustic_delay_seconds,
        start_hz=start_hz,
        end_hz=end_hz,
        amplitude=amplitude,
        fade_seconds=fade_seconds,
        noise_seed=noise_seed,
    )

    wav_file = FIXTURES_DIR / "phase2_recorded_style_probe.wav"
    with wave.open(str(wav_file), "wb") as writer:
        writer.setnchannels(1)
        writer.setsampwidth(2)
        writer.setframerate(sample_rate_hz)
        writer.writeframes((samples * 32767.0).astype("<i2").tobytes())

    payload = {
        "name": "phase2_recorded_style_probe",
        "description": (
            "Committed PCM WAV fixture with attenuated/colored chirp, direct-path bleed, "
            "room-style echoes, hum/noise, soft clipping, and post-chirp ring-down. "
            "This is a deterministic recorded-style fixture; replace or supplement it "
            "with real device recordings as soon as measurement data is available."
        ),
        "wav_file": wav_file.name,
        "sample_rate_hz": sample_rate_hz,
        "probe_config": {
            "start_hz": start_hz,
            "end_hz": end_hz,
            "duration_seconds": chirp_seconds,
            "amplitude": amplitude,
            "fade_seconds": fade_seconds,
            "pre_roll_seconds": pre_roll_seconds,
            "post_roll_seconds": post_roll_seconds,
        },
        "expected": {
            "latency_ms": 8.04,
            "latency_tolerance_ms": 1.0,
            "min_alignment_confidence": 0.80,
            "max_alignment_confidence": 0.98,
            "min_signal_to_noise_db": 20.0,
            "primary_peak_hz": 1640.0,
            "primary_peak_tolerance_hz": 20.0,
            "secondary_peak_hz": 2925.0,
            "secondary_peak_tolerance_hz": 35.0,
            "min_decay_rate_per_second": 3.5,
            "max_decay_rate_per_second": 6.5,
        },
    }
    write_json(FIXTURES_DIR / "phase2_recorded_style_probe.json", payload)


def build_recorded_style_probe(
    *,
    sample_rate_hz: int,
    pre_roll_seconds: float,
    chirp_seconds: float,
    post_roll_seconds: float,
    acoustic_delay_seconds: float,
    start_hz: float,
    end_hz: float,
    amplitude: float,
    fade_seconds: float,
    noise_seed: int,
) -> np.ndarray:
    rng = np.random.default_rng(noise_seed)
    total_seconds = pre_roll_seconds + chirp_seconds + post_roll_seconds + 0.06
    sample_count = int(round(total_seconds * sample_rate_hz))
    time = np.arange(sample_count, dtype=np.float64) / sample_rate_hz
    samples = rng.normal(0.0, 0.0014, sample_count)
    samples += 0.0016 * np.sin(2.0 * math.pi * 60.0 * time)
    samples += 0.0007 * np.sin(2.0 * math.pi * 180.0 * time + 0.4)

    chirp = generate_log_chirp(
        ChirpSpec(start_hz, end_hz, chirp_seconds, amplitude, fade_seconds),
        sample_rate_hz,
    )
    colored = color_chirp(chirp, sample_rate_hz)
    chirp_start = int(round((pre_roll_seconds + acoustic_delay_seconds) * sample_rate_hz))

    add_at(samples, colored, chirp_start, gain=1.0)
    add_at(samples, colored, chirp_start + int(round(0.024 * sample_rate_hz)), gain=0.24)
    add_at(
        samples,
        np.convolve(colored, np.ones(9) / 9.0, mode="same"),
        chirp_start + int(round(0.061 * sample_rate_hz)),
        gain=0.11,
    )

    ring_start = chirp_start + chirp.size + int(round(0.014 * sample_rate_hz))
    ring_time = np.arange(samples.size - ring_start, dtype=np.float64) / sample_rate_hz
    ring = 0.062 * np.exp(-4.9 * ring_time) * np.sin(2.0 * math.pi * 1640.0 * ring_time + 0.2)
    ring += 0.034 * np.exp(-7.5 * ring_time) * np.sin(2.0 * math.pi * 2925.0 * ring_time - 0.3)
    ring += 0.018 * np.exp(-12.0 * ring_time) * np.sin(2.0 * math.pi * 4810.0 * ring_time + 1.1)
    samples[ring_start:] += ring

    return np.clip(np.tanh(1.22 * samples) / 1.22, -0.98, 0.98)


def color_chirp(chirp: np.ndarray, sample_rate_hz: int) -> np.ndarray:
    frequencies = np.fft.rfftfreq(chirp.size, d=1.0 / sample_rate_hz)
    magnitude = 0.56 / np.maximum(1.0, (frequencies / 800.0) ** 0.12)
    magnitude *= 1.0 - 0.32 * np.exp(-0.5 * ((frequencies - 3600.0) / 520.0) ** 2)
    magnitude *= 1.0 - 0.22 * np.exp(-0.5 * ((frequencies - 7800.0) / 840.0) ** 2)
    magnitude *= 1.0 + 0.055 * np.cos(2.0 * math.pi * frequencies * 0.0018)
    phase_shift = np.exp(-1j * 2.0 * math.pi * frequencies * 0.00055)
    colored = np.fft.irfft(np.fft.rfft(chirp) * magnitude * phase_shift, n=chirp.size)
    return colored + 0.018 * np.power(colored, 3)


def add_at(target: np.ndarray, signal: np.ndarray, start: int, *, gain: float) -> None:
    end = min(target.size, start + signal.size)
    if end > start:
        target[start:end] += gain * signal[: end - start]


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
